export type LocalUser={userId:string;fullName:string;displayName:string;email:string;demo:boolean};
export type Inquiry={id:string;code:string;message:string;name:string;phone:string;created_at:number};
type Account=LocalUser&{salt:string;passwordHash:string;favorites:string[];inquiries:Inquiry[]};
type Store={version:1;accounts:Account[];session:string|null};
const KEY='vertice.mobile.accounts.v1';
function randomId(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(v=>v.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
function read():Store{try{const raw=localStorage.getItem(KEY);if(!raw)return {version:1,accounts:[],session:null};const value=JSON.parse(raw) as Store;if(value.version!==1||!Array.isArray(value.accounts))throw new Error();return value;}catch{throw new Error('Não foi possível ler os dados locais. Verifique se o navegador permite armazenamento.');}}
function save(store:Store){try{localStorage.setItem(KEY,JSON.stringify(store));window.dispatchEvent(new Event('vertice:account'));}catch{throw new Error('Não foi possível guardar seus dados. Libere espaço ou habilite o armazenamento do navegador.');}}
function publicUser(a:Account):LocalUser{return {userId:a.userId,fullName:a.fullName,displayName:a.fullName,email:a.email,demo:a.demo};}
function active(store:Store){const a=store.accounts.find(a=>a.userId===store.session);if(!a)throw new Error('Entre na sua conta local para continuar.');return a;}
export function currentUser(){const s=read(),a=s.accounts.find(a=>a.userId===s.session);return a?publicUser(a):null;}
async function hash(password:string,salt:string){if(!crypto.subtle)throw new Error('Abra a prévia por localhost ou HTTPS para usar a conta local.');const bytes=Uint8Array.from(salt.match(/.{2}/g)!.map(v=>parseInt(v,16)));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes,iterations:150000},key,256);return [...new Uint8Array(bits)].map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function register(name:string,email:string,password:string){name=name.trim();email=email.trim().toLowerCase();if(name.length<2||name.length>100)throw new Error('Preencha seu nome.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>150)throw new Error('Preencha um e-mail válido.');if(password.length<8||password.length>128)throw new Error('A senha de teste precisa ter de 8 a 128 caracteres.');const initial=read();if(initial.accounts.some(a=>a.email===email))throw new Error('Este e-mail já tem uma conta neste navegador. Use Entrar.');const salt=[...crypto.getRandomValues(new Uint8Array(16))].map(v=>v.toString(16).padStart(2,'0')).join('');const passwordHash=await hash(password,salt);const s=read();if(s.accounts.some(a=>a.email===email))throw new Error('Este e-mail já tem uma conta neste navegador.');const a:Account={userId:randomId(),fullName:name,displayName:name,email,demo:false,salt,passwordHash,favorites:[],inquiries:[]};s.accounts.push(a);s.session=a.userId;save(s);return publicUser(a);}
export async function login(email:string,password:string){const s=read(),a=s.accounts.find(a=>a.email===email.trim().toLowerCase()&&!a.demo);if(!a||await hash(password,a.salt)!==a.passwordHash)throw new Error('E-mail ou senha incorretos.');const fresh=read();fresh.session=a.userId;save(fresh);return publicUser(a);}
export function enterDemo(){const s=read();let a=s.accounts.find(a=>a.demo);if(!a){a={userId:randomId(),fullName:'Visitante Vértice',displayName:'Visitante Vértice',email:'demo@vertice.local',demo:true,salt:'',passwordHash:'',favorites:[],inquiries:[]};s.accounts.push(a);}s.session=a.userId;save(s);return publicUser(a);}
export function logout(){const s=read();s.session=null;save(s);}
export function favorites(){return [...active(read()).favorites];}
export function setFavorite(code:string,saved:boolean){const s=read(),a=active(s);a.favorites=saved?[...new Set([...a.favorites,code])]:a.favorites.filter(c=>c!==code);save(s);return [...a.favorites];}
export function inquiries(){return [...active(read()).inquiries].sort((a,b)=>b.created_at-a.created_at);}
export function addInquiry(input:Omit<Inquiry,'id'|'created_at'>){if(input.name.trim().length<2||input.name.length>100||!/^\d{10,11}$/.test(input.phone.replace(/\D/g,''))||input.message.trim().length<8||input.message.length>1000)throw new Error('Confira seu nome, telefone e mensagem.');const s=read(),a=active(s);const item={...input,name:input.name.trim(),phone:input.phone.replace(/\D/g,''),message:input.message.trim(),id:randomId(),created_at:Date.now()};a.inquiries.unshift(item);save(s);return item;}
export function updateName(name:string){const s=read(),a=active(s);if(name.trim().length<2||name.length>100)throw new Error('Preencha um nome válido.');a.fullName=name.trim();a.displayName=a.fullName;save(s);return publicUser(a);}
